### ISSUE TITLE
Executing insertImage command directly

### ISSUE THREAD

**Issue by norman784** [tiff/wysihtml5#271]
How do I execute directly the command imageInsert?

Cause I try to execute

``` javascript
editor.composer.commands.exec('insertImage', {src:'http://myimageurl'});
```

and get

```
code: 2
message: "INVALID_NODE_TYPE_ERR: DOM Range Exception 2"
name: "INVALID_NODE_TYPE_ERR"
stack: "Error: The container of an boundary-point of a Range was being set to either a node of an invalid type or a node with an ancestor of an invalid type.

at Object.setStartAfter (wysihtml5-0.3.0.min.js:2240:47)
at wysihtml5.Selection.Base.extend.setAfter (wysihtml5-0.3.0.min.js:5976:13)
at Object.wysihtml5.commands.insertImage.exec (wysihtml5-0.3.0.min.js:7419:28)
at wysihtml5.Commands.Base.extend.exec wysihtml5-0.3.0.min.js:6792:23)
at <anonymous>:2:26
at Object.InjectedScript._evaluateOn (<anonymous>:444:39)
at Object.InjectedScript._evaluateAndWrap (<anonymous>:403:52)
at Object.InjectedScript.evaluate (<anonymous>:339:21)"
```

The way im doing right now its using the insertHtml command but don't know if the best approach having a command that do that

Regards

**Comment by zrod** [comment]
Can you provide more details?

Where are you calling this from? Are you using some sort of modal?

I've had a similar issue, in my case the editor was losing focus. I worked around by getting a caret bookmark, focusing the editor, setting the bookmark, and then calling .exec('insertImage', ...).

Example:

``` javascript
var caretBookmark;

toolbar.find( 'a[data-wysihtml5-command="createLink"]' ).click( function() {
   caretBookmark = editor.composer.selection.getBookmark();
   // ...
   modal( 'show' );
   // ...
});

// Later on saving...
if ( caretBookmark ) {
    editor.composer.selection.setBookmark( caretBookmark );
}

editor.currentView.element.focus();
editor.composer.commands.exec( 'insertImage', { src: imageSrc, alt: imageAlt } );

// ...
modal( 'hide' );
```

**Comment by norman784** [comment]
Im just call the insertImage command on a normal textarea, i would try now this.

**Comment by kurijov** [comment]
@zrod thx.

editor.currentView.element.focus(); 

was enough for me.

**Comment by micksear** [comment]
@kurijov - Thanks - that worked for me too!

**Comment by lcoq** [comment]
:+1: I also had this problem, solved by the solution above, thanks !

**Comment by davidmccabe** [comment]
This worked for me too.
